// Iced Blue
// Copyright 2010-2011 Sean Farrell

#ifndef _QGL_KEY_H_
#define _QGL_KEY_H_

#include "config.h"

namespace qgl
{
    /**
     * Symbolic Key Mappings.
     **/
    enum Key
    {
        UNKNOWN_KEY         = 0,
        BACKSPACE_KEY       = 8,
        TAB_KEY             = 9,
        CLEAR_KEY           = 12,
        RETURN_KEY          = 13,
        PAUSE_KEY           = 19,
        ESCAPE_KEY          = 27,
        SPACE_KEY           = 32,
        EXCLAIM_KEY         = 33,
        QUOTEDBL_KEY        = 34,
        HASH_KEY            = 35,
        DOLLAR_KEY          = 36,
        AMPERSAND_KEY       = 38,
        QUOTE_KEY           = 39,
        LEFTPAREN_KEY       = 40,
        RIGHTPAREN_KEY      = 41,
        ASTERISK_KEY        = 42,
        PLUS_KEY            = 43,
        COMMA_KEY           = 44,
        MINUS_KEY           = 45,
        PERIOD_KEY          = 46,
        SLASH_KEY           = 47,
        ZERO_KEY            = 48,
        ONE_KEY             = 49,
        TWO_KEY             = 50,
        THREE_KEY           = 51,
        FOUR_KEY            = 52,
        FIVE_KEY            = 53,
        SIX_KEY             = 54,
        SEVEN_KEY           = 55,
        EIGHT_KEY           = 56,
        NINE_KEY            = 57,
        COLON_KEY           = 58,
        SEMICOLON_KEY       = 59,
        LESS_KEY            = 60,
        EQUALS_KEY          = 61,
        GREATER_KEY         = 62,
        QUESTION_KEY        = 63,
        AT_KEY              = 64,
        LEFT_BRACKET_KEY    = 91,
        BACKSLASH_KEY       = 92,
        RIGHT_BRACKET_KEY   = 93,
        CARET_KEY           = 94,
        UNDERSCORE_KEY      = 95,
        BACKQUOTE_KEY       = 96,
        A_KEY               = 97,
        B_KEY               = 98,
        C_KEY               = 99,
        D_KEY               = 100,
        E_KEY               = 101,
        F_KEY               = 102,
        G_KEY               = 103,
        H_KEY               = 104,
        I_KEY               = 105,
        J_KEY               = 106,
        K_KEY               = 107,
        L_KEY               = 108,
        M_KEY               = 109,
        N_KEY               = 110,
        O_KEY               = 111,
        P_KEY               = 112,
        Q_KEY               = 113,
        R_KEY               = 114,
        S_KEY               = 115,
        T_KEY               = 116,
        U_KEY               = 117,
        V_KEY               = 118,
        W_KEY               = 119,
        X_KEY               = 120,
        Y_KEY               = 121,
        Z_KEY               = 122,
        DELETE_KEY          = 127,
        KP0_KEY             = 256,
        KP1_KEY             = 257,
        KP2_KEY             = 258,
        KP3_KEY             = 259,
        KP4_KEY             = 260,
        KP5_KEY             = 261,
        KP6_KEY             = 262,
        KP7_KEY             = 263,
        KP8_KEY             = 264,
        KP9_KEY             = 265,
        KP_PERIOD_KEY       = 266,
        KP_DIVIDE_KEY       = 267,
        KP_MULTIPLY_KEY     = 268,
        KP_MINUS_KEY        = 269,
        KP_PLUS_KEY         = 270,
        KP_ENTER_KEY        = 271,
        KP_EQUALS_KEY       = 272,
        UP_KEY              = 273,
        DOWN_KEY            = 274,
        RIGHT_KEY           = 275,
        LEFT_KEY            = 276,
        INSERT_KEY          = 277,
        HOME_KEY            = 278,
        END_KEY             = 279,
        PAGEUP_KEY          = 280,
        PAGEDOWN_KEY        = 281,
        F1_KEY              = 282,
        F2_KEY              = 283,
        F3_KEY              = 284,
        F4_KEY              = 285,
        F5_KEY              = 286,
        F6_KEY              = 287,
        F7_KEY              = 288,
        F8_KEY              = 289,
        F9_KEY              = 290,
        F10_KEY             = 291,
        F11_KEY             = 292,
        F12_KEY             = 293,
        F13_KEY             = 294,
        F14_KEY             = 295,
        F15_KEY             = 296,
        NUMLOCK             = 300,
        CAPSLOCK_KEY        = 301,
        SCROLLOCK_KEY       = 302,
        RSHIFT_KEY          = 303,
        LSHIFT_KEY          = 304,
        RCTRL_KEY           = 305,
        LCTRL_KEY           = 306,
        RALT_KEY            = 307,
        LALT_KEY            = 308,
        RMETA_KEY           = 309,
        LMETA_KEY           = 310,
        LSUPER_KEY          = 311,
        RSUPER_KEY          = 312,
        MODE_KEY            = 313,
        COMPOSE_KEY         = 314,
        HELP_KEY            = 315,
        PRINT_KEY           = 316,
        SYSREQ_KEY          = 317,
        BREAK_KEY           = 318,
        MENU_KEY            = 319,
        POWER_KEY           = 320,
        EURO_KEY            = 321,
        UNDO_KEY            = 322
    };
}

#endif
